/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { GroupItemRequestBuilderNavigationMetadata, type GroupItemRequestBuilder } from './item/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /groups
 */
export interface GroupsRequestBuilder extends BaseRequestBuilder<GroupsRequestBuilder> {
    /**
     * Gets an item from the Chatbot-UI.Beta.groups.item collection
     * @param groupId The unique identifier of group
     * @returns {GroupItemRequestBuilder}
     */
     byGroupId(groupId: string) : GroupItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const GroupsRequestBuilderUriTemplate = "{+baseurl}/groups";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const GroupsRequestBuilderNavigationMetadata: Record<Exclude<keyof GroupsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byGroupId: {
        navigationMetadata: GroupItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["group%2Did"],
    },
};
/* tslint:enable */
/* eslint-enable */
