/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { OnenoteRequestBuilderNavigationMetadata, type OnenoteRequestBuilder } from './onenote/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /groups/{group-id}
 */
export interface GroupItemRequestBuilder extends BaseRequestBuilder<GroupItemRequestBuilder> {
    /**
     * The onenote property
     */
    get onenote(): OnenoteRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const GroupItemRequestBuilderUriTemplate = "{+baseurl}/groups/{group%2Did}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const GroupItemRequestBuilderNavigationMetadata: Record<Exclude<keyof GroupItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    onenote: {
        navigationMetadata: OnenoteRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
