/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createOutlookUserFromDiscriminatorValue, type OutlookUser } from '../../models/index';
// @ts-ignore
import { createODataErrorFromDiscriminatorValue, type ODataError } from '../../models/oDataErrors/index';
// @ts-ignore
import { MasterCategoriesRequestBuilderRequestsMetadata, type MasterCategoriesRequestBuilder } from './masterCategories/index';
// @ts-ignore
import { TaskFoldersRequestBuilderRequestsMetadata, type TaskFoldersRequestBuilder } from './taskFolders/index';
// @ts-ignore
import { TaskGroupsRequestBuilderRequestsMetadata, type TaskGroupsRequestBuilder } from './taskGroups/index';
// @ts-ignore
import { TasksRequestBuilderRequestsMetadata, type TasksRequestBuilder } from './tasks/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides operations to manage the outlook property of the microsoft.graph.user entity.
 */
export interface OutlookRequestBuilder extends BaseRequestBuilder<OutlookRequestBuilder> {
    /**
     * Provides operations to manage the masterCategories property of the microsoft.graph.outlookUser entity.
     * @deprecated  as of 2024-07/PrivatePreview:copilotExportAPI
     */
    get masterCategories(): MasterCategoriesRequestBuilder;
    /**
     * Provides operations to manage the taskFolders property of the microsoft.graph.outlookUser entity.
     * @deprecated  as of 2024-07/PrivatePreview:copilotExportAPI
     */
    get taskFolders(): TaskFoldersRequestBuilder;
    /**
     * Provides operations to manage the taskGroups property of the microsoft.graph.outlookUser entity.
     * @deprecated  as of 2024-07/PrivatePreview:copilotExportAPI
     */
    get taskGroups(): TaskGroupsRequestBuilder;
    /**
     * Provides operations to manage the tasks property of the microsoft.graph.outlookUser entity.
     * @deprecated  as of 2024-07/PrivatePreview:copilotExportAPI
     */
    get tasks(): TasksRequestBuilder;
    /**
     * Selective Outlook services available to the user. Read-only. Nullable.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<OutlookUser>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     * @deprecated  as of 2024-07/PrivatePreview:copilotExportAPI
     */
     get(requestConfiguration?: RequestConfiguration<OutlookRequestBuilderGetQueryParameters> | undefined) : Promise<OutlookUser | undefined>;
    /**
     * Selective Outlook services available to the user. Read-only. Nullable.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     * @deprecated  as of 2024-07/PrivatePreview:copilotExportAPI
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<OutlookRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Selective Outlook services available to the user. Read-only. Nullable.
 */
export interface OutlookRequestBuilderGetQueryParameters {
    /**
     * Expand related entities
     */
    expand?: string[];
    /**
     * Select properties to be returned
     */
    select?: string[];
}
/**
 * Uri template for the request builder.
 */
export const OutlookRequestBuilderUriTemplate = "{+baseurl}/me/outlook{?%24expand,%24select}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const OutlookRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "expand": "%24expand",
    "select": "%24select",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const OutlookRequestBuilderNavigationMetadata: Record<Exclude<keyof OutlookRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    masterCategories: {
        requestsMetadata: MasterCategoriesRequestBuilderRequestsMetadata,
    },
    taskFolders: {
        requestsMetadata: TaskFoldersRequestBuilderRequestsMetadata,
    },
    taskGroups: {
        requestsMetadata: TaskGroupsRequestBuilderRequestsMetadata,
    },
    tasks: {
        requestsMetadata: TasksRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const OutlookRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: OutlookRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createOutlookUserFromDiscriminatorValue,
        queryParametersMapper: OutlookRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
