version: '3.8'
services:
  app:
    command: sh -c "cd /workspace/supabase-project && npm run dev"
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"

  studio:
    ports:
      - "54321:3000"

  db:
    ports:
      - "5432:5432"

  kong:
    ports:
      - "8000:8000"
      - "8443:8443"