/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { SiteItemRequestBuilderRequestsMetadata, type SiteItemRequestBuilder } from './item/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /sites/{site-id}/sites
 */
export interface SitesRequestBuilder extends BaseRequestBuilder<SitesRequestBuilder> {
    /**
     * Provides operations to manage the sites property of the microsoft.graph.site entity.
     * @param siteId1 The unique identifier of site
     * @returns {SiteItemRequestBuilder}
     */
     bySiteId1(siteId1: string) : SiteItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const SitesRequestBuilderUriTemplate = "{+baseurl}/sites/{site%2Did}/sites";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SitesRequestBuilderNavigationMetadata: Record<Exclude<keyof SitesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    bySiteId1: {
        requestsMetadata: SiteItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["site%2Did1"],
    },
};
/* tslint:enable */
/* eslint-enable */
