/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { SectionGroupItemRequestBuilderNavigationMetadata, type SectionGroupItemRequestBuilder } from './item/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups
 */
export interface SectionGroupsRequestBuilder extends BaseRequestBuilder<SectionGroupsRequestBuilder> {
    /**
     * Gets an item from the Chatbot-UI.Beta.groups.item.onenote.notebooks.item.sectionGroups.item collection
     * @param sectionGroupId The unique identifier of sectionGroup
     * @returns {SectionGroupItemRequestBuilder}
     */
     bySectionGroupId(sectionGroupId: string) : SectionGroupItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const SectionGroupsRequestBuilderUriTemplate = "{+baseurl}/groups/{group%2Did}/onenote/notebooks/{notebook%2Did}/sectionGroups";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SectionGroupsRequestBuilderNavigationMetadata: Record<Exclude<keyof SectionGroupsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    bySectionGroupId: {
        navigationMetadata: SectionGroupItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["sectionGroup%2Did"],
    },
};
/* tslint:enable */
/* eslint-enable */
