/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { OnenotePageItemRequestBuilderNavigationMetadata, type OnenotePageItemRequestBuilder } from './item/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections/{onenoteSection-id}/pages
 */
export interface PagesRequestBuilder extends BaseRequestBuilder<PagesRequestBuilder> {
    /**
     * Gets an item from the Chatbot-UI.Beta.groups.item.onenote.notebooks.item.sectionGroups.item.sections.item.pages.item collection
     * @param onenotePageId The unique identifier of onenotePage
     * @returns {OnenotePageItemRequestBuilder}
     */
     byOnenotePageId(onenotePageId: string) : OnenotePageItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PagesRequestBuilderUriTemplate = "{+baseurl}/groups/{group%2Did}/onenote/notebooks/{notebook%2Did}/sectionGroups/{sectionGroup%2Did}/sections/{onenoteSection%2Did}/pages";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PagesRequestBuilderNavigationMetadata: Record<Exclude<keyof PagesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byOnenotePageId: {
        navigationMetadata: OnenotePageItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["onenotePage%2Did"],
    },
};
/* tslint:enable */
/* eslint-enable */
