/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { SectionGroupsRequestBuilderNavigationMetadata, type SectionGroupsRequestBuilder } from './sectionGroups/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /groups/{group-id}/onenote/notebooks/{notebook-id}
 */
export interface NotebookItemRequestBuilder extends BaseRequestBuilder<NotebookItemRequestBuilder> {
    /**
     * The sectionGroups property
     */
    get sectionGroups(): SectionGroupsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const NotebookItemRequestBuilderUriTemplate = "{+baseurl}/groups/{group%2Did}/onenote/notebooks/{notebook%2Did}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const NotebookItemRequestBuilderNavigationMetadata: Record<Exclude<keyof NotebookItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    sectionGroups: {
        navigationMetadata: SectionGroupsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
