/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { OnenoteRequestBuilderNavigationMetadata, type OnenoteRequestBuilder } from './onenote/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /me
 */
export interface MeRequestBuilder extends BaseRequestBuilder<MeRequestBuilder> {
    /**
     * The onenote property
     */
    get onenote(): OnenoteRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const MeRequestBuilderUriTemplate = "{+baseurl}/me";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MeRequestBuilderNavigationMetadata: Record<Exclude<keyof MeRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    onenote: {
        navigationMetadata: OnenoteRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
