/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
<<<<<<< HEAD
import { MailFoldersRequestBuilderRequestsMetadata, type MailFoldersRequestBuilder } from './mailFolders/index';
// @ts-ignore
import { MessagesRequestBuilderRequestsMetadata, type MessagesRequestBuilder } from './messages/index';
// @ts-ignore
import { SendMailRequestBuilderRequestsMetadata, type SendMailRequestBuilder } from './sendMail/index';
// @ts-ignore
import { TodoRequestBuilderNavigationMetadata, TodoRequestBuilderRequestsMetadata, type TodoRequestBuilder } from './todo/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';
=======
import { createUserFromDiscriminatorValue, type User } from '../models/index';
// @ts-ignore
import { createODataErrorFromDiscriminatorValue, type ODataError } from '../models/oDataErrors/index';
// @ts-ignore
import { CalendarRequestBuilderNavigationMetadata, CalendarRequestBuilderRequestsMetadata, type CalendarRequestBuilder } from './calendar/index';
// @ts-ignore
import { DrivesRequestBuilderNavigationMetadata, DrivesRequestBuilderRequestsMetadata, type DrivesRequestBuilder } from './drives/index';
// @ts-ignore
import { MailFoldersRequestBuilderNavigationMetadata, MailFoldersRequestBuilderRequestsMetadata, type MailFoldersRequestBuilder } from './mailFolders/index';
// @ts-ignore
import { MessagesRequestBuilderNavigationMetadata, MessagesRequestBuilderRequestsMetadata, type MessagesRequestBuilder } from './messages/index';
// @ts-ignore
import { TodoRequestBuilderNavigationMetadata, TodoRequestBuilderRequestsMetadata, type TodoRequestBuilder } from './todo/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';
>>>>>>> mgt

/**
 * Provides operations to manage the user singleton.
 */
export interface MeRequestBuilder extends BaseRequestBuilder<MeRequestBuilder> {
    /**
<<<<<<< HEAD
=======
     * Provides operations to manage the calendar property of the microsoft.graph.user entity.
     * @deprecated  as of 2024-07/PrivatePreview:copilotExportAPI
     */
    get calendar(): CalendarRequestBuilder;
    /**
     * Provides operations to manage the drives property of the microsoft.graph.user entity.
     * @deprecated  as of 2024-07/PrivatePreview:copilotExportAPI
     */
    get drives(): DrivesRequestBuilder;
    /**
>>>>>>> mgt
     * Provides operations to manage the mailFolders property of the microsoft.graph.user entity.
     * @deprecated  as of 2024-07/PrivatePreview:copilotExportAPI
     */
    get mailFolders(): MailFoldersRequestBuilder;
    /**
     * Provides operations to manage the messages property of the microsoft.graph.user entity.
     * @deprecated  as of 2024-07/PrivatePreview:copilotExportAPI
     */
    get messages(): MessagesRequestBuilder;
    /**
<<<<<<< HEAD
     * Provides operations to call the sendMail method.
     */
    get sendMail(): SendMailRequestBuilder;
    /**
=======
>>>>>>> mgt
     * Provides operations to manage the todo property of the microsoft.graph.user entity.
     * @deprecated  as of 2024-07/PrivatePreview:copilotExportAPI
     */
    get todo(): TodoRequestBuilder;
    /**
     * Retrieve the properties and relationships of user object. This operation returns by default only a subset of the more commonly used properties for each user. These default properties are noted in the Properties section. To get properties that are not returned by default, do a GET operation for the user and specify the properties in a $select OData query option. Because the user resource supports extensions, you can also use the GET operation to get custom properties and extension data in a user instance. Customers through Microsoft Entra ID for customers can also use this API operation to retrieve their details.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<User>}
     * @throws {ODataError} error when the service returns a 4XX or 5XX status code
     * @deprecated  as of 2024-07/PrivatePreview:copilotExportAPI
     * @see {@link https://learn.microsoft.com/graph/api/user-get?view=graph-rest-beta|Find more info here}
     */
     get(requestConfiguration?: RequestConfiguration<MeRequestBuilderGetQueryParameters> | undefined) : Promise<User | undefined>;
    /**
     * Retrieve the properties and relationships of user object. This operation returns by default only a subset of the more commonly used properties for each user. These default properties are noted in the Properties section. To get properties that are not returned by default, do a GET operation for the user and specify the properties in a $select OData query option. Because the user resource supports extensions, you can also use the GET operation to get custom properties and extension data in a user instance. Customers through Microsoft Entra ID for customers can also use this API operation to retrieve their details.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     * @deprecated  as of 2024-07/PrivatePreview:copilotExportAPI
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<MeRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Retrieve the properties and relationships of user object. This operation returns by default only a subset of the more commonly used properties for each user. These default properties are noted in the Properties section. To get properties that are not returned by default, do a GET operation for the user and specify the properties in a $select OData query option. Because the user resource supports extensions, you can also use the GET operation to get custom properties and extension data in a user instance. Customers through Microsoft Entra ID for customers can also use this API operation to retrieve their details.
 */
export interface MeRequestBuilderGetQueryParameters {
    /**
     * Expand related entities
     */
    expand?: string[];
    /**
     * Select properties to be returned
     */
    select?: string[];
}
/**
 * Uri template for the request builder.
 */
export const MeRequestBuilderUriTemplate = "{+baseurl}/me{?%24expand,%24select}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const MeRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "expand": "%24expand",
    "select": "%24select",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MeRequestBuilderNavigationMetadata: Record<Exclude<keyof MeRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
<<<<<<< HEAD
=======
    calendar: {
        requestsMetadata: CalendarRequestBuilderRequestsMetadata,
        navigationMetadata: CalendarRequestBuilderNavigationMetadata,
    },
    drives: {
        requestsMetadata: DrivesRequestBuilderRequestsMetadata,
        navigationMetadata: DrivesRequestBuilderNavigationMetadata,
    },
>>>>>>> mgt
    mailFolders: {
        requestsMetadata: MailFoldersRequestBuilderRequestsMetadata,
    },
    messages: {
        requestsMetadata: MessagesRequestBuilderRequestsMetadata,
<<<<<<< HEAD
    },
    sendMail: {
        requestsMetadata: SendMailRequestBuilderRequestsMetadata,
=======
        navigationMetadata: MessagesRequestBuilderNavigationMetadata,
>>>>>>> mgt
    },
    todo: {
        requestsMetadata: TodoRequestBuilderRequestsMetadata,
        navigationMetadata: TodoRequestBuilderNavigationMetadata,
<<<<<<< HEAD
=======
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const MeRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: MeRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            XXX: createODataErrorFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createUserFromDiscriminatorValue,
        queryParametersMapper: MeRequestBuilderGetQueryParametersMapper,
>>>>>>> mgt
    },
};
/* tslint:enable */
/* eslint-enable */
