/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { MailFoldersRequestBuilderRequestsMetadata, type MailFoldersRequestBuilder } from './mailFolders/index';
// @ts-ignore
import { MessagesRequestBuilderRequestsMetadata, type MessagesRequestBuilder } from './messages/index';
// @ts-ignore
import { SendMailRequestBuilderRequestsMetadata, type SendMailRequestBuilder } from './sendMail/index';
// @ts-ignore
import { TodoRequestBuilderNavigationMetadata, TodoRequestBuilderRequestsMetadata, type TodoRequestBuilder } from './todo/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /me
 */
export interface MeRequestBuilder extends BaseRequestBuilder<MeRequestBuilder> {
    /**
     * Provides operations to manage the mailFolders property of the microsoft.graph.user entity.
     */
    get mailFolders(): MailFoldersRequestBuilder;
    /**
     * Provides operations to manage the messages property of the microsoft.graph.user entity.
     */
    get messages(): MessagesRequestBuilder;
    /**
     * Provides operations to call the sendMail method.
     */
    get sendMail(): SendMailRequestBuilder;
    /**
     * Provides operations to manage the todo property of the microsoft.graph.user entity.
     */
    get todo(): TodoRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const MeRequestBuilderUriTemplate = "{+baseurl}/me";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MeRequestBuilderNavigationMetadata: Record<Exclude<keyof MeRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    mailFolders: {
        requestsMetadata: MailFoldersRequestBuilderRequestsMetadata,
    },
    messages: {
        requestsMetadata: MessagesRequestBuilderRequestsMetadata,
    },
    sendMail: {
        requestsMetadata: SendMailRequestBuilderRequestsMetadata,
    },
    todo: {
        requestsMetadata: TodoRequestBuilderRequestsMetadata,
        navigationMetadata: TodoRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
