/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { DrivesRequestBuilderNavigationMetadata, type DrivesRequestBuilder } from './drives/index';
// @ts-ignore
import { GroupsRequestBuilderNavigationMetadata, type GroupsRequestBuilder } from './groups/index';
// @ts-ignore
import { MeRequestBuilderNavigationMetadata, type MeRequestBuilder } from './me/index';
// @ts-ignore
import { SitesRequestBuilderNavigationMetadata, SitesRequestBuilderRequestsMetadata, type SitesRequestBuilder } from './sites/index';
// @ts-ignore
import { apiClientProxifier, registerDefaultDeserializer, registerDefaultSerializer, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type RequestAdapter } from '@microsoft/kiota-abstractions';

/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface Beta extends BaseRequestBuilder<Beta> {
    /**
     * The drives property
     */
    get drives(): DrivesRequestBuilder;
    /**
     * The groups property
     */
    get groups(): GroupsRequestBuilder;
    /**
     * The me property
     */
    get me(): MeRequestBuilder;
    /**
     * Provides operations to manage the collection of site entities.
     */
    get sites(): SitesRequestBuilder;
}
/**
 * Instantiates a new {@link Beta} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-ignore
export function createBeta(requestAdapter: RequestAdapter) {
    if (requestAdapter.baseUrl === undefined || requestAdapter.baseUrl === null || requestAdapter.baseUrl === "") {
        requestAdapter.baseUrl = "https://graph.microsoft.com/beta";
    }
    const pathParameters: Record<string, unknown> = {
        "baseurl": requestAdapter.baseUrl,
    };
    return apiClientProxifier<Beta>(requestAdapter, pathParameters, BetaNavigationMetadata, undefined);
}
/**
 * Uri template for the request builder.
 */
export const BetaUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const BetaNavigationMetadata: Record<Exclude<keyof Beta, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    drives: {
        navigationMetadata: DrivesRequestBuilderNavigationMetadata,
    },
    groups: {
        navigationMetadata: GroupsRequestBuilderNavigationMetadata,
    },
    me: {
        navigationMetadata: MeRequestBuilderNavigationMetadata,
    },
    sites: {
        requestsMetadata: SitesRequestBuilderRequestsMetadata,
        navigationMetadata: SitesRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
