/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { SectionsRequestBuilderNavigationMetadata, type SectionsRequestBuilder } from './sections/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /groups/{group-id}/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}
 */
export interface SectionGroupItemRequestBuilder extends BaseRequestBuilder<SectionGroupItemRequestBuilder> {
    /**
     * The sections property
     */
    get sections(): SectionsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const SectionGroupItemRequestBuilderUriTemplate = "{+baseurl}/groups/{group%2Did}/onenote/notebooks/{notebook%2Did}/sectionGroups/{sectionGroup%2Did}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SectionGroupItemRequestBuilderNavigationMetadata: Record<Exclude<keyof SectionGroupItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    sections: {
        navigationMetadata: SectionsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
