/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { OnenotePageItemRequestBuilderNavigationMetadata, type OnenotePageItemRequestBuilder } from './item/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /me/onenote/pages
 */
export interface PagesRequestBuilder extends BaseRequestBuilder<PagesRequestBuilder> {
    /**
     * Gets an item from the Chatbot-UI.Beta.me.onenote.pages.item collection
     * @param onenotePageId The unique identifier of onenotePage
     * @returns {OnenotePageItemRequestBuilder}
     */
     byOnenotePageId(onenotePageId: string) : OnenotePageItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const PagesRequestBuilderUriTemplate = "{+baseurl}/me/onenote/pages";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const PagesRequestBuilderNavigationMetadata: Record<Exclude<keyof PagesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byOnenotePageId: {
        navigationMetadata: OnenotePageItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["onenotePage%2Did"],
    },
};
/* tslint:enable */
/* eslint-enable */
