/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { OnenoteSectionItemRequestBuilderNavigationMetadata, type OnenoteSectionItemRequestBuilder } from './item/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /me/onenote/notebooks/{notebook-id}/sectionGroups/{sectionGroup-id}/sections
 */
export interface SectionsRequestBuilder extends BaseRequestBuilder<SectionsRequestBuilder> {
    /**
     * Gets an item from the Chatbot-UI.Beta.me.onenote.notebooks.item.sectionGroups.item.sections.item collection
     * @param onenoteSectionId The unique identifier of onenoteSection
     * @returns {OnenoteSectionItemRequestBuilder}
     */
     byOnenoteSectionId(onenoteSectionId: string) : OnenoteSectionItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const SectionsRequestBuilderUriTemplate = "{+baseurl}/me/onenote/notebooks/{notebook%2Did}/sectionGroups/{sectionGroup%2Did}/sections";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SectionsRequestBuilderNavigationMetadata: Record<Exclude<keyof SectionsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byOnenoteSectionId: {
        navigationMetadata: OnenoteSectionItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["onenoteSection%2Did"],
    },
};
/* tslint:enable */
/* eslint-enable */
